import type { Category, MenuItem, MenuPayload, Order, TableSession } from "@/lib/types";
import { restaurantConfig } from "@/config/restaurant";

export const demoCategories: Category[] = [
  { id: "starters", name: "Закуски", sortOrder: 1 },
  { id: "salads", name: "Салаты", sortOrder: 2 },
  { id: "mains", name: "Горячее", sortOrder: 3 },
  { id: "desserts", name: "Десерты", sortOrder: 4 },
  { id: "drinks", name: "Напитки", sortOrder: 5 },
];

const images = {
  toast:
    "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1000&q=82",
  table:
    "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1000&q=82",
  salad:
    "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1000&q=82",
  soup:
    "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=82",
  pasta:
    "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1000&q=82",
  meat:
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=82",
  pizza:
    "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1000&q=82",
  dessert:
    "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1000&q=82",
  drink:
    "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1000&q=82",
};

const sauceGroup = (id: string) => ({
  id: `${id}-sauce`,
  name: "Добавить соус",
  required: false,
  minSelected: 0,
  maxSelected: 2,
  modifiers: [
    { id: `${id}-sauce-pepper`, name: "Перечный", price: 12000 },
    { id: `${id}-sauce-truffle`, name: "Трюфельный", price: 16000 },
    { id: `${id}-sauce-adjika`, name: "Аджика", price: 9000 },
  ],
});

const temperatureGroup = {
  id: "steak-temperature",
  name: "Прожарка",
  required: true,
  minSelected: 1,
  maxSelected: 1,
  modifiers: [
    { id: "steak-medium-rare", name: "Medium rare", price: 0 },
    { id: "steak-medium", name: "Medium", price: 0 },
    { id: "steak-well-done", name: "Well done", price: 0 },
  ],
};

const volumeGroup = (id: string) => ({
  id: `${id}-volume`,
  name: "Объём",
  required: true,
  minSelected: 1,
  maxSelected: 1,
  modifiers: [
    { id: `${id}-300`, name: "300 мл", price: 0 },
    { id: `${id}-500`, name: "500 мл", price: 14000 },
  ],
});

export const demoMenuItems: MenuItem[] = [
  {
    id: "bruschetta",
    categoryId: "starters",
    name: "Брускетта с печёным перцем",
    description: "Страчателла, сладкий перец, базилик и хрустящий тартин",
    price: 54000,
    image: images.toast,
    weight: "190 г",
    popular: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "tartar",
    categoryId: "starters",
    name: "Тартар из говядины",
    description: "Каперсы, горчица, копчёный желток и картофель пай",
    price: 76000,
    image: images.meat,
    weight: "170 г",
    popular: true,
    available: true,
    modifierGroups: [sauceGroup("tartar")],
  },
  {
    id: "hummus",
    categoryId: "starters",
    name: "Хумус с томатами",
    description: "Тёплая пита, пряное масло и семена кориандра",
    price: 43000,
    image: images.table,
    weight: "240 г",
    spicy: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "green-salad",
    categoryId: "salads",
    name: "Зелёный салат",
    description: "Авокадо, брокколи, огурец, зелень и цитрусовая заправка",
    price: 59000,
    image: images.salad,
    weight: "250 г",
    available: true,
    modifierGroups: [],
  },
  {
    id: "tomato-salad",
    categoryId: "salads",
    name: "Томаты и молодой сыр",
    description: "Сезонные томаты, имеретинский сыр и масло тархуна",
    price: 61000,
    image: images.salad,
    weight: "270 г",
    popular: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "warm-aubergine",
    categoryId: "salads",
    name: "Тёплый баклажан",
    description: "Томаты, кинза, кешью и кисло-сладкий соус",
    price: 62000,
    image: images.table,
    weight: "260 г",
    spicy: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "pumpkin-soup",
    categoryId: "mains",
    name: "Тыквенный крем-суп",
    description: "Креветки, кокосовое молоко и пряное масло",
    price: 58000,
    image: images.soup,
    weight: "330 г",
    spicy: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "pasta-crab",
    categoryId: "mains",
    name: "Паста с крабом",
    description: "Свежая паста, бисque, томаты и эстрагон",
    price: 98000,
    image: images.pasta,
    weight: "320 г",
    popular: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "steak",
    categoryId: "mains",
    name: "Стейк из мраморной говядины",
    description: "Выдержанная говядина, печёный чеснок и мясной соус",
    price: 169000,
    image: images.meat,
    weight: "280 г",
    popular: true,
    available: true,
    modifierGroups: [temperatureGroup, sauceGroup("steak")],
  },
  {
    id: "chicken",
    categoryId: "mains",
    name: "Цыплёнок на углях",
    description: "Кукуруза, копчёная сметана и соус из трав",
    price: 89000,
    image: images.meat,
    weight: "390 г",
    available: true,
    modifierGroups: [sauceGroup("chicken")],
  },
  {
    id: "khachapuri",
    categoryId: "mains",
    name: "Хачапури из печи",
    description: "Три вида сыра, сливочное масло и хрустящая корочка",
    price: 72000,
    image: images.pizza,
    weight: "410 г",
    available: true,
    modifierGroups: [
      {
        id: "khachapuri-extra",
        name: "Дополнить",
        required: false,
        minSelected: 0,
        maxSelected: 2,
        modifiers: [
          { id: "khachapuri-egg", name: "Яичный желток", price: 8000 },
          { id: "khachapuri-cheese", name: "Больше сыра", price: 15000 },
        ],
      },
    ],
  },
  {
    id: "honey-cake",
    categoryId: "desserts",
    name: "Медовик с солёной карамелью",
    description: "Тонкие коржи, сметанный крем и гречишный мёд",
    price: 49000,
    image: images.dessert,
    weight: "150 г",
    popular: true,
    available: true,
    modifierGroups: [],
  },
  {
    id: "pavlova",
    categoryId: "desserts",
    name: "Павлова с сезонными ягодами",
    description: "Хрустящая меренга, крем маскарпоне и ягодный соус",
    price: 52000,
    image: images.dessert,
    weight: "170 г",
    available: false,
    modifierGroups: [],
  },
  {
    id: "lemonade",
    categoryId: "drinks",
    name: "Лимонад тархун — груша",
    description: "Домашний кордиал, груша, тархун и содовая",
    price: 32000,
    image: images.drink,
    available: true,
    modifierGroups: [volumeGroup("lemonade")],
  },
  {
    id: "tea",
    categoryId: "drinks",
    name: "Чай смородина — шалфей",
    description: "Чёрная смородина, шалфей, мёд и чёрный чай",
    price: 42000,
    image: images.drink,
    weight: "600 мл",
    available: true,
    modifierGroups: [],
  },
];

export const demoMenuPayload: MenuPayload = {
  table: {
    id: "table-7",
    number: restaurantConfig.demoTable.number,
    token: restaurantConfig.demoTable.token,
  },
  categories: demoCategories,
  items: demoMenuItems,
};

export const demoSeedOrders: Order[] = [
  {
    id: "demo-order-1042",
    publicNumber: "1042",
    sessionId: "demo-session-203",
    sessionPublicNumber: "203",
    sessionStatus: "open",
    tableNumber: 3,
    visitorToken: "seed-1042",
    status: "new",
    comment: "Соус подайте отдельно, пожалуйста",
    total: 152000,
    createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60_000).toISOString(),
    viewed: false,
    items: [
      {
        id: "line-1042-1",
        menuItemId: "tartar",
        name: "Тартар из говядины",
        basePrice: 76000,
        quantity: 2,
        modifiers: [],
        unitPrice: 76000,
        lineTotal: 152000,
      },
    ],
  },
  {
    id: "demo-order-1041",
    publicNumber: "1041",
    sessionId: "demo-session-202",
    sessionPublicNumber: "202",
    sessionStatus: "open",
    tableNumber: 9,
    visitorToken: "seed-1041",
    status: "accepted",
    comment: "",
    total: 144000,
    createdAt: new Date(Date.now() - 12 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    viewed: true,
    items: [
      {
        id: "line-1041-1",
        menuItemId: "pasta-crab",
        name: "Паста с крабом",
        basePrice: 98000,
        quantity: 1,
        modifiers: [],
        unitPrice: 98000,
        lineTotal: 98000,
      },
      {
        id: "line-1041-2",
        menuItemId: "lemonade",
        name: "Лимонад тархун — груша",
        basePrice: 32000,
        quantity: 1,
        modifiers: [{ id: "lemonade-500", name: "500 мл", price: 14000 }],
        unitPrice: 46000,
        lineTotal: 46000,
      },
      {
        id: "line-1041-3",
        menuItemId: "khachapuri",
        name: "Хачапури из печи",
        basePrice: 72000,
        quantity: 1,
        modifiers: [{ id: "khachapuri-egg", name: "Яичный желток", price: 8000 }],
        unitPrice: 80000,
        lineTotal: 80000,
      },
    ].slice(0, 2),
  },
  {
    id: "demo-order-1039",
    publicNumber: "1039",
    sessionId: "demo-session-201",
    sessionPublicNumber: "201",
    sessionStatus: "closed",
    tableNumber: 5,
    visitorToken: "seed-1039",
    status: "completed",
    comment: "",
    total: 110000,
    createdAt: new Date(Date.now() - 51 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 60_000).toISOString(),
    viewed: true,
    items: [
      {
        id: "line-1039-1",
        menuItemId: "tomato-salad",
        name: "Томаты и молодой сыр",
        basePrice: 61000,
        quantity: 1,
        modifiers: [],
        unitPrice: 61000,
        lineTotal: 61000,
      },
      {
        id: "line-1039-2",
        menuItemId: "honey-cake",
        name: "Медовик с солёной карамелью",
        basePrice: 49000,
        quantity: 1,
        modifiers: [],
        unitPrice: 49000,
        lineTotal: 49000,
      },
    ],
  },
  {
    id: "demo-order-1038",
    publicNumber: "1038",
    sessionId: "demo-session-202",
    sessionPublicNumber: "202",
    sessionStatus: "open",
    tableNumber: 9,
    visitorToken: "seed-1038",
    status: "completed",
    comment: "Без кинзы, пожалуйста",
    total: 59000,
    createdAt: new Date(Date.now() - 38 * 60_000).toISOString(),
    updatedAt: new Date(Date.now() - 19 * 60_000).toISOString(),
    viewed: true,
    items: [
      {
        id: "line-1038-1",
        menuItemId: "green-salad",
        name: "Зелёный салат",
        basePrice: 59000,
        quantity: 1,
        modifiers: [],
        unitPrice: 59000,
        lineTotal: 59000,
      },
    ],
  },
];

export const demoSeedSessions: TableSession[] = [
  {
    id: "demo-session-203",
    publicNumber: "203",
    tableNumber: 3,
    status: "open",
    total: 152000,
    createdAt: demoSeedOrders[0].createdAt,
    updatedAt: demoSeedOrders[0].updatedAt,
    orders: [demoSeedOrders[0]],
  },
  {
    id: "demo-session-202",
    publicNumber: "202",
    tableNumber: 9,
    status: "open",
    total: 203000,
    createdAt: demoSeedOrders[3].createdAt,
    updatedAt: demoSeedOrders[1].updatedAt,
    orders: [demoSeedOrders[3], demoSeedOrders[1]],
  },
  {
    id: "demo-session-201",
    publicNumber: "201",
    tableNumber: 5,
    status: "closed",
    total: 110000,
    createdAt: demoSeedOrders[2].createdAt,
    updatedAt: demoSeedOrders[2].updatedAt,
    closedAt: demoSeedOrders[2].updatedAt,
    orders: [demoSeedOrders[2]],
  },
];
